# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='post',
        ),
        migrations.AddField(
            model_name='thread',
            name='post',
            field=models.ManyToManyField(related_name='answer', to='forum.Post'),
        ),
    ]
