# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20161008_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='modify',
        ),
    ]
