# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_thread_modify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modify',
        ),
    ]
