# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 04:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20161009_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['pub_date__month']),
        ),
    ]
