# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 05:00
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20161011_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['create__month']),
        ),
    ]
