# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20161011_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
