# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 09:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20161021_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
