# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 23:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20161022_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
