# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20161022_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='post',
        ),
        migrations.AddField(
            model_name='thread',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='forum.Post'),
            preserve_default=False,
        ),
    ]
