# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
