# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_post_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closed_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
