# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20161116_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
