# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20161214_1237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([]),
        ),
    ]
