# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0025_auto_20161214_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([('user', 'content')]),
        ),
    ]
