# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20161216_0001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([]),
        ),
    ]
