# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_auto_20161216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
