# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_auto_20161218_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_answers', to='forum.Thread'),
            preserve_default=False,
        ),
    ]
