# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
