# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0034_thread_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correctanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctanswer_answer', to='forum.Thread'),
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctanswer_post', to='forum.Post'),
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctanswer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
