# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_auto_20170104_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='users/%Y/%m/%d'),
        ),
    ]
